# Generated by Django 4.2.2 on 2023-06-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_path',
            field=models.CharField(blank=True, db_index=True, max_length=8),
        ),
    ]
