# Generated by Django 4.2.2 on 2023-06-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_url_short_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_path',
            field=models.CharField(db_index=True, default='', max_length=8),
        ),
    ]
